language: php
sudo: required
dist: trusty

env:
  - PROJECT_NAME=irc-bot

jobs:
  include:
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "nightly"

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

script:
  - composer install --no-dev -a
  - composer archive --format=tar --file=$PROJECT_NAME
  - tar tvf $PROJECT_NAME.tar

before_deploy:
  - xz -9 $PROJECT_NAME.tar
  - mv $PROJECT_NAME.tar.xz $PROJECT_NAME-$TRAVIS_TAG.tar.xz

deploy:
  provider: releases
  # https://docs.travis-ci.com/user/deployment/releases/
  # Create token with privilege in https://github.com/settings/tokens and set as env var.
  # It must have the public_repo or repo scope to upload assets
  # $ travis env set -p GITHUB_API_TOKEN abcdefabcdefabcdef
  # or via https://travis-ci.org/eventum/irc-bot/settings
  api_key: $GITHUB_API_TOKEN
  file_glob: true
  file:
    - $PROJECT_NAME-*.tar.xz
  skip_cleanup: true
  overwrite: true
  on:
    repo: eventum/irc-bot
    php: '5.6'
    tags: true

# vim:ts=2:sw=2:et
