language: php
sudo: required
dist: trusty

jobs:
  include:
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "nightly"

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

# vim:ts=2:sw=2:et
